
version: '3.8'

services:
  web:
    build: ./src
    command: |
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    volumes: 
      - ./src/:/usr/src/app/
    ports: 
      - 8002:8000
    environment: 
      - DATABASE_URL=postgresql://guane-test:guane-test@db/guane-test_dev
      - CELERY_BROKER_URL=amqp://guest:guest@fastapi-rabbit:5672
      - CELERY_RESULT_BACKEND:redis://:password123@redis:6379/0
    depends_on: 
      - redis
      - rabbit
    networks: 
      - fastapi

  db:
    image: postgres:13-alpine
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    expose: 
      - 5432
    environment: 
      - POSTGRES_USER=guane-test
      - POSTGRES_PASSWORD=guane-test
      - POSTGRES_DB=guane-test_dev 
    networks: 
      - fastapi

  worker:
    build: ./src
    command: celery -A worker.celery worker --loglevel=INFO
    volumes:
      - ./src:/usr/src/app
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@fastapi-rabbit:5672
      - CELERY_RESULT_BACKEND:redis://:password123@redis:6379/0
    depends_on: 
      - web
      - redis
      - rabbit
    networks: 
      - fastapi

  rabbit:
    image: rabbitmq:latest
    environment: 
      - RABBITMQ_DEFAULT_USER=guest
      - RABBIT_DEFAULT_PASS=guest
    ports: 
      - 5672:5672
    networks: 
      fastapi:
        aliases: 
          - fastapi-rabbit

  redis:
    image: redis:6-alpine
    command: redis-server --requirepass password123
    environment: 
      - REDIS_PASSWORD=password123
    networks:
      - fastapi

volumes: 
  postgres_data:
networks: 
  fastapi:
    external: True


