"""Add column id_user to dogs table

Revision ID: 216cd9bd14d1
Revises: d94f747126a5
Create Date: 2021-06-14 05:56:25.634871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.schema import ForeignKey


# revision identifiers, used by Alembic.
revision = '216cd9bd14d1'
down_revision = 'd94f747126a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dogs', sa.Column('id_user', sa.Integer, ForeignKey('users.id')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dogs', 'id_user')
    # ### end Alembic commands ###
